name: Build and Deploy

on:
 pull_request:
   branches:
     - master
   types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Decode Keystore
      run: echo ${{ secrets.B64_ENCORDED_KEYSTORE }} | base64 --decode > ./app/release.keystore

    - name: Generate AAB
      run: ./gradlew :app:bundleRelease
      env:
       RELEASE_KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
       RELEASE_KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Deploy
      id: deploy
      uses: r0adkll/upload-google-play@v1.0.15
      with:
         serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
         packageName: com.punyo.nitechvacancyviewer
         releaseFile: app/build/outputs/bundle/release/app-release.aab
         track: production
         whatsNewDirectory: whatsnew/
         mappingFile: app/build/outputs/mapping/release/mapping.txt
         debugSymbols: app/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib
