name: Build and Deploy

on:
 pull_request:
   branches:
     - master
   types: [closed]
   
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Decode Keystore
      run: echo ${{ secrets.B64_ENCORDED_KEYSTORE }} | base64 --decode > ./app/release.keystore

    - name: Generate AAB
      run: ./gradlew :app:bundleRelease
      env:
       RELEASE_KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
       RELEASE_KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
       RELEASE_KEYSTORE_ALIAS: ${{ secrets.KEY_ALIAS }}

    - name: Upload AAB and mapping.txt
      uses: actions/upload-artifact@v4
      with:
        name: latest-build-result
        path: |
            app/build/outputs/bundle/release/app-release.aab
            app/build/outputs/mapping/release/mapping.txt

  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4

     - name: Download AAB and mapping.txt
       uses: actions/download-artifact@v4
       with:
          name: latest-build-result
          
     - name: Upload AAB
       uses: r0adkll/upload-google-play@v1.0.15
       id: uploadAAB
       with:
         serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
         packageName: com.punyo.nitechvacancyviewer
         releaseFile: bundle/release/app-release.aab
         track: production
         whatsNewDirectory: whatsnew/
         mappingFile: mapping/release/mapping.txt
